#!/bin/bash
source $HOME/.config/tide/scripts/menu_functions

function kill_sessions_option() {
    local sessions=($( tmux list-sessions -F "#{session_name}" 2> /dev/null ))

    if [[ ! -z $sessions ]]; then
        print_menu_header Sessions
        print_menu_body ${sessions[@]}
        echo "  c: cancel"

        read -p ">> " session_keys_string
        IFS=',' read -ra sessions_keys <<< "$session_keys_string"

        # Only delete sessions if none of the session keys are c
        if [[ ! "${sessions_keys[*]}" =~ "c" ]]; then
            for session_key in ${sessions_keys[@]}; do
                # Delete tmux sessions only if session keys are valid
                if [[ $(isKeyValid $session_key ${sessions[@]}) == "true" ]]; then
                    tmux kill-session -t ${sessions[$session_key-1]}
                else
                    print_invalid_key_error $session_key
                fi
            done
        fi
    fi
}
